### ISSUE TITLE
Online demo? 

### ISSUE THREAD

**Issue by tesar-tech** [JByfordRew/BlazorStyledTextArea#1]
Is there an online demo for this library? 

If you want I can prepare yml, which builds project from `demo/net6.0/v0.1/BlazorStyledTextAreaDemoWasm)/Client/` and prepares it for github pages. Then it is few clicks in settings.

**Comment by JByfordRew** [comment]
Never done that, I will investigate, many thanks. Would be cool.

**Comment by JByfordRew** [comment]
Perhaps you could host the demo and I'll link to it. AOT preferable though to show it off at its best.

**Comment by JByfordRew** [comment]
Thank you for this PR, I really wanted AOT and seems I needed to use Azure Static Web App to do this.  The online demo is now available as a link from the Readme.  Closing this issue and PR
